title: '[Feat] 간결하고 명확한 제목 작성'

body:
  - type: markdown
    attributes:
      value: |
        ## ✅ 작업 내용 요약
        주요 구현/수정 사항을 요약해 주세요.

  - type: input
    id: issue
    attributes:
      label: 관련 이슈 번호
      description: 이 PR과 연결된 이슈 번호를 작성해 주세요.
      placeholder: '#123'

  - type: checkboxes
    id: changes
    attributes:
      label: 작업 내용
      description: 아래에서 해당하는 항목을 체크해 주세요.
      options:
        - label: ✨ Feature
        - label: 🐞 BugFix
        - label: 🔨 Refactor
        - label: 🌏 Deploy
        - label: 🎨 Publishing
        - label: 📃 Docs
        - label: ✅ Test

  - type: textarea
    id: description
    attributes:
      label: 상세 설명
      description: 변경된 작업 내용을 구체적으로 작성해 주세요.
      placeholder: |
        예) 
        - 로그인 페이지 UI 구성
        - 사용자 입력값 유효성 검사 추가
        - 로그인 실패 시 에러 메시지 처리
      value: ''

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: PR을 제출하기 전 아래 항목들을 확인해 주세요.
      options:
        - label: 기능이 정상 동작함
        - label: 디자인 가이드를 따름
        - label: 엣지 케이스 및 예외 처리 확인함
        - label: 테스트 코드를 작성하거나 수동 테스트를 완료함
        - label: PR 설명을 충분히 작성함
