name: Release on main merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Generate Release Notes from PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git and fetch tags
        run: git fetch --tags

      - name: Get last semver tag and date
        id: get_last_tag
        run: |
          LAST_TAG=$(git tag --list '[0-9]*' --sort=-v:refname | head -n 1)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="0.0.0"
          fi
          TAG_DATE=$(git log -1 --format=%aI "$LAST_TAG" || date -Iseconds)
          echo "last_tag=$LAST_TAG" >> $GITHUB_OUTPUT
          echo "last_tag_date=$TAG_DATE" >> $GITHUB_OUTPUT

      - name: Get merged PRs and their bodies
        id: changelog
        uses: actions/github-script@v6
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              base: "main",
              per_page: 100
            });

            const since = new Date("${{ steps.get_last_tag.outputs.last_tag_date }}");
            const mergedPRs = prs.filter(pr => pr.merged_at && new Date(pr.merged_at) > since);

            const formatted = mergedPRs.map(pr => {
              const cleanBody = pr.body?.trim() || "_No description provided._";
              return `### ${pr.title} (#${pr.number}) by @${pr.user.login}\n\n${cleanBody}`;
            });

            const changelog = formatted.join("\n\n---\n\n");
            // Write changelog to file to avoid context issues
            const fs = require('fs');
            fs.writeFileSync('CHANGELOG.md', changelog);
            // Still set the output for compatibility
            return changelog;
          result-encoding: string

      - name: Bump SemVer version
        id: versioning
        run: |
          OLD_VERSION=${{ steps.get_last_tag.outputs.last_tag }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          git config user.name "Github-Release-Bot"
          git config user.email "dltmdgus1412@gmail.com"
          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          name: ${{ steps.versioning.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
